### ISSUE TITLE
建议还是 push 到 github 上来吧

### ISSUE THREAD

**Issue by tvvocold** [qex/keystart#1]
提供未加密的js，方便其他人提交PR/提出建议

**Comment by tvvocold** [comment]
哦抱歉，刚找到，原来在另一个 branch。

**Comment by tvvocold** [comment]
BTW， 能否设置为在新窗口打开?
如何在默认页加入 .org后缀的网站?

**Comment by tvvocold** [comment]
@qex

**Comment by qex** [comment]
必须的~ 等等我放 original 的版本上来~

**Comment by qex** [comment]
@tvvocold 已经 push 了 update ... 代码写的比较粗糙还请见谅 ...

新窗口打开需要用到 window.open ... 可能会被大部分浏览器拦下来 ... 

如果想要改可以把 js 文件里的 `window.location.href` 改成 `window.open` ...

**Comment by tvvocold** [comment]
赞！
如何在默认页加入 .org后缀的网站? 我尝试在js里加入

```
setCookie("_D", "http://www.domain.org");
```

但是Push后未生效
另外，`window.location.href` 是指哪个 function 里的?

**Comment by qex** [comment]
@tvvocold 默认页修改之后需要清除饼干才能生效的 ... 全清掉的话会导致所有自定义设置丢失 ...

一个温柔一点的办法是在浏览器 console 里面输入 `deleteCookie( 'FIRSTTIME' );` ...

这样只有所有默认提供的链接会被覆盖 ...

`window.location.href` 在代码的 28 行和 40 行 ... 分别对应键盘事件和鼠标点击事件 ...

改成 `window.open( urlcache[code] );` 即可在新窗口打开 ...

**Comment by tvvocold** [comment]
Thx!
Lincense 是个亮点！学习了
