### ISSUE TITLE
“不会因为浏览器的关闭而失效”，为什么？

### ISSUE THREAD

**Issue by g2384** [qex/keystart#3]
我也做过这种网页，觉得很实用，现在也在用我自己做的。
报道上说“不会因为浏览器的关闭而失效”，真的吗，怎么用？

**Comment by hqfzone** [comment]
cookie保存啊~

**Comment by g2384** [comment]
我还以为是desktop应用，或者Chrome托盘什么的高级技术………………达到“关闭页面后，仍能使用快捷键“效果
直接修改源码不就好了么。
